; Конфигурация PlatformIO для ESP32-C3 Mini / SuperMini

[env:esp32-c3]
platform = espressif32 ; пакет с тулчейном и ESP32 Arduino core
board = esp32-c3-devkitm-1 ; обобщённая плата C3, подходит и для SuperMini-вариантов
framework = arduino ; используем Arduino framework, как ты и планировал
monitor_speed = 115200 ; скорость серийного монитора для отладки

lib_deps =
    madhephaestus/ESP32Servo ; библиотека для ШИМ-управления сервой на ESP32 (бери версию 3.x+, старые не поддерживают C3)
    robtillaart/INA226

build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1 ; ОБЯЗАТЕЛЬНО для большинства C3 SuperMini — без этого флага Serial может не работать через USB